name: Event Filter
on:
  workflow_dispatch # 5
  # 1
  # push:
  #   branches: [main, develop]
  #   paths:
  #     - "src/**"

  # 2
  # pull_request:
  #   types: ["opened", "synchronize", "close"]

  # 3
  # push:
  #   path:
  #     - "src/frontend/**"
  #     - "src/backend/**"
  #     - "src/config/**"

  # 4
  # push:
  #   branches: ["main", "develop","feature/*"]

jobs:
  hello_world: # job의 이름
    runs-on: ubuntu-latest # job을 실행하는 환경
    steps: #step 정의
      - name: Hello World #step 이름
        run: echo "Hello, World!" # run : <cli 명령어>

