# 워크플로우 -> 자동화 할 작업의 설계서 -> action.yml

# name: first workflow
# on: push # 이벤트 트리거
# jobs:
#   hello_world: # job의 이름
#     runs-on: ubuntu-latest # job을 실행하는 환경
#     steps: #step 정의
#       - name: Hello World #step 이름
#         run: echo "Hello, World!" # run : <cli 명령어>

name: first workflow
on:
push:
  branches: [main, develop]
jobs:
  # npm run lint
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: install deps
        run: npm ci

      - name: run build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: install deps
        run: npm ci

      - name: run build
        run: npm run test

  # lint -> build
  # bild job 이전에 lint job이 실행되야하ㅓㅁ
  # 순차적으로 실행되야함
  # 단일 선행작업 -> needs: <job name.
  # 복수 선행작업 -> needs: [ <job name 1>, ,<job name 2>]
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: install deps
        run: npm ci

      - name: run build
        run: npm run build
