# 워크플로우 -> 자동화 할 작업의 설계서 -> action.yml

# name: first workflow
# on: push # 이벤트 트리거
# jobs:
#   hello_world: # job의 이름
#     runs-on: ubuntu-latest # job을 실행하는 환경
#     steps: #step 정의
#       - name: Hello World #step 이름
#         run: echo "Hello, World!" # run : <cli 명령어>

name: first workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: install nodejs
        uses: actions/setup-node
        with:
          node-version: "22"

      - name: install deps
        run: npm ci

      -name: run build
        run: npm run build
