name: Auto Issue on PR Open
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  detect-template:
    runs-on: ubuntu-latest
    outputs:
      template: ${{ steps.detect.outputs.template }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect template type (with debug)
        id: detect
        run: |
          title="${{ github.event.pull_request.title }}"
          echo "📝 PR Title: $title"

          template="custom.md"
          if [[ "$title" =~ [bB][uU][gG] ]]; then
            template="bug_report.md"
          elif [[ "$title" =~ [fF][eE][aA][tT][uU][rR][eE] ]]; then
            template="feature_request.md"
          fi

          echo "📄 Selected template: $template"
          echo "template=$template" >> $GITHUB_OUTPUT

  create-issue:
    needs: detect-template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Issue from selected template
        uses: peter-evans/create-issue-from-file@v4
        with:
          content-filepath: .github/ISSUE_TEMPLATE/${{ needs.detect-template.outputs.template }}
          title: "[Auto] PR #${{ github.event.pull_request.number }} 검증"
          labels: auto-generated
          assignees: ${{ github.event.pull_request.user.login }}
