name: Basic ci
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: run deps
        run: npm ci

      - name: install test
        run: npm run test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: install deps
        run: npm ci

      - name: run build
        run: npm run build
