name: Close Linked Issues on Merge
on:
  pull_request:
    types: [closed]

permissions:
  issues: write
  pull-requests: read

jobs:
  close-issues:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Close linked issues
        uses: peter-evans/close-issue@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
